services:
  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: "root2"
      POSTGRES_PASSWORD: "root2"
      POSTGRES_DB: "ny_taxi"
    volumes:
      - "ny_taxi_postgres_data:/var/lib/postgresql"
    ports:
      - "5429:5432"
    networks:
      - airflow

    
networks:
  airflow:
    external: true
    name: airflow_default

volumes:
  ny_taxi_postgres_data: